name: pciutils # you probably want to 'snapcraft register <name>'
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: snap to run lspci # 79 char long summary
description: |
  snap to run lspci using pciutils version 3.5.5.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
    lspci:
        command: usr/local/sbin/lspci
        plugs: [hardware-observe]

parts:
    pciutils:
        plugin: make
        source: https://www.kernel.org/pub/software/utils/pciutils/pciutils-3.5.5.tar.gz

